use actix_web::{get, web, App, HttpResponse, HttpServer, Responder};
use serde::Serialize;
use log::info;

// Definición de la estructura Carrera
#[derive(Debug, Serialize)]
struct Carrera {
    nombre: String,
    materias: Vec<String>,
}

// Función para obtener las carreras y sus materias
fn obtener_carreras() -> Vec<Carrera> {
    vec![
        // Carrera: Ingeniería en Sistemas Computacionales
        Carrera {
            nombre: "Ingeniería en Sistemas Computacionales".to_string(),
            materias: vec![
                "Cálculo diferencial".to_string(),
                "Matemáticas discretas".to_string(),
                "Fundamentos de programación".to_string(),
                "Taller de administración".to_string(),
                "Fundamentos de investigación".to_string(),
                "Taller de ética".to_string(),
                "Cálculo integral".to_string(),
                "Álgebra lineal".to_string(),
                "Programación orientada a objetos".to_string(),
                "Contabilidad financiera".to_string(),
                "Química".to_string(),
                "Probabilidad y estadística".to_string(),
                "Cálculo vectorial".to_string(),
                "Investigación de operaciones".to_string(),
                "Estructura de datos".to_string(),
                "Cultura empresarial".to_string(),
                "Desarrollo Sustentable".to_string(),
                "Física general".to_string(),
                "Ecuaciones diferenciales".to_string(),
                "Fundamentos de base de datos".to_string(),
                "Tópicos avanzados de programación".to_string(),
                "Simulación".to_string(),
                "Métodos numéricos".to_string(),
                "Principios eléctricos y aplic. digitales".to_string(),
                "Fundamentos de ingeniería de software".to_string(),
                "Taller de base de datos".to_string(),
                "Sistemas operativos".to_string(),
                "Graficación".to_string(),
                "Fundamentos de telecomunicaciones".to_string(),
                "Arquitectura de computadoras".to_string(),
                "Ingeniería de software".to_string(),
                "Administración de base de datos".to_string(),
                "Lenguajes y autómatas I".to_string(),
                "Taller de sistemas operativos".to_string(),
                "Redes de computadoras".to_string(),
                "Lenguajes de interfaz".to_string(),
                "Gestión de proyectos de software".to_string(),
                "Lenguajes y autómatas II".to_string(),
                "Taller de investigación I".to_string(),
                "Conmutación y enrutamiento de redes de datos".to_string(),
                "Sistemas programables".to_string(),
                "Taller de investigación II".to_string(),
                "Administración de redes".to_string(),
                "Programación lógica y funcional".to_string(),
                "Programación web".to_string(),
                "Inteligencia artificial".to_string(),
            ],
        },
        // Carrera: Ingeniería Industrial
        Carrera {
            nombre: "Ingeniería Industrial".to_string(),
            materias: vec![
                "Fundamentos de investigación".to_string(),
                "Cálculo diferencial".to_string(),
                "Desarrollo humano".to_string(),
                "Fundamentos de gestión empresarial".to_string(),
                "Dinámica social".to_string(),
                "Fundamentos de química".to_string(),
                "Software de aplicación ejecutivo".to_string(),
                "Cálculo integral".to_string(),
                "Contabilidad orientada a los negocios".to_string(),
                "Legislación laboral".to_string(),
                "Taller de ética".to_string(),
                "Fundamentos de física".to_string(),
                "Marco legal de las organizaciones".to_string(),
                "Probabilidad y estad. descrip.".to_string(),
                "Costos empresariales".to_string(),
                "Habilidades directivas I".to_string(),
                "Economía empresarial".to_string(),
                "Álgebra lineal".to_string(),
                "INSTR. de PRES. e,presarial".to_string(),
                "Estadística inferencial I".to_string(),
                "Ingeniería de procesos".to_string(),
                "Habilidades directivas II".to_string(),
                "Entorno macroeconómico".to_string(),
                "Investig. de operaciones".to_string(),
                "Finanzas en las organizaciones".to_string(),
                "Estadística inferencial II".to_string(),
                "Gestión de la producción I".to_string(),
                "Gestión de capital humano".to_string(),
                "Desarrollo sustentable".to_string(),
                "Mercadotecnia".to_string(),
                "Ingeniería económica".to_string(),
                "El emprendedor y la innovación".to_string(),
                "Gestión de la producción II".to_string(),
                "Admon. de la salud y seg. ocupacional".to_string(),
                "Calidad aplicada a la gestión empresarial".to_string(),
                "Sist. de inf. de la MKT".to_string(),
                "Plan de negocios".to_string(),
                "Taller de investigación I".to_string(),
                "Diseño organizacional".to_string(),
                "Mercadotecnia electrónica".to_string(),
                "Taller de investigación II".to_string(),
                "Gestión estratégica".to_string(),
                "Cadena de suministros".to_string(),
            ],
        },
        // Carrera: Ingeniería en Tecnologías de la Información y Comunicaciones
        Carrera {
            nombre: "Ingeniería en Tecnologías de la Información y Comunicaciones".to_string(),
            materias: vec![
                "Cálculo diferencial".to_string(),
                "Fundamentos de programación".to_string(),
                "Matemáticas discretas".to_string(),
                "Introducción a las TIC'S".to_string(),
                "Taller de ética".to_string(),
                "Fundamentos de investigación".to_string(),
                "Cálculo integral".to_string(),
                "Programación orientada a objetos".to_string(),
                "Matemáticas discretas II".to_string(),
                "Probabilidad y estadística".to_string(),
                "Contabilidad y costos".to_string(),
                "Administración gerencial".to_string(),
                "Matemáticas aplicadas a comunicaciones".to_string(),
                "Estructura y organización de datos".to_string(),
                "Álgebra lineal".to_string(),
                "Fundamentos de bases de datos".to_string(),
                "Electricidad y magnetismo".to_string(),
                "Desarrollo sustentable".to_string(),
                "Análisis de señales y sistemas de Comunicación".to_string(),
                "Programación II".to_string(),
                "Matemáticas para la toma de decisiones".to_string(),
                "Taller de base de datos".to_string(),
                "Circuitos eléctricos y electrónicos".to_string(),
                "Ingeniería de software".to_string(),
                "Redes de computadoras".to_string(),
                "Tecnologías inalámbricas".to_string(),
                "Desarrollo de emprendedores".to_string(),
                "Taller de investigación I".to_string(),
                "Sistemas operativos I".to_string(),
                "Programación web".to_string(),
                "Redes emergentes".to_string(),
                "Desarrollo de aplicaciones para dispositivos móviles".to_string(),
                "Ingeniería del conocimiento".to_string(),
                "Taller de investigación II".to_string(),
                "Sistemas operativos II".to_string(),
                "Negocios electrónicos I".to_string(),
                "Administración y seguridad de redes".to_string(),
                "Interacción humano computadora".to_string(),
                "Auditoría en tecnologías de información".to_string(),
                "Negocios electrónicos II".to_string(),
                "Residencias".to_string(),
            ],
        },
        // Carrera: Ingeniería en Electrónica
        Carrera {
            nombre: "Ingeniería en Electrónica".to_string(),
            materias: vec![
                "Cálculo diferencial".to_string(),
                "Mecánica clásica".to_string(),
                "Química".to_string(),
                "Taller de ética".to_string(),
                "Fundamentos de investigación".to_string(),
                "Comunicación humana".to_string(),
                "Cálculo integral".to_string(),
                "Probabilidad y estadística".to_string(),
                "Desarrollo sustentable".to_string(),
                "Mediciones eléctricas".to_string(),
                "Tópicos selectos de física".to_string(),
                "Desarrollo humano".to_string(),
                "Cálculo vectorial".to_string(),
                "Electromagnetismo".to_string(),
                "Álgebra lineal".to_string(),
                "Física de semiconductores".to_string(),
                "Programación estructurada".to_string(),
                "Ecuaciones diferenciales".to_string(),
                "Circuitos eléctricos I".to_string(),
                "Marco legal de la empresa".to_string(),
                "Análisis numérico".to_string(),
                "Diseño digital".to_string(),
                "Programación visual".to_string(),
                "Circuitos eléctricos II".to_string(),
                "Diodos y transistores".to_string(),
                "Teoría electromagnética".to_string(),
                "Máquinas eléctricas".to_string(),
                "Diseño digital con VHDL".to_string(),
                "Desarrollo profesional".to_string(),
                "Control I".to_string(),
                "Diseño con transistores".to_string(),
                "Fundamentos financieros".to_string(),
                "Microcontroladores".to_string(),
                "Taller de investigación I".to_string(),
                "Control II".to_string(),
                "Amplificadores operacionales".to_string(),
                "Instrumentación".to_string(),
                "Optoeléctronica".to_string(),
                "Introducción a las telecomunicaciones".to_string(),
                "Taller de investigación II".to_string(),
                "Control digital".to_string(),
                "Controladores lógicos programables".to_string(),
                "Electrónica de potencia".to_string(),
                "Administración gerencial".to_string(),
                "Desarrollo y evaluación de proyectos".to_string(),
                "Residencia profesional".to_string(),
            ],
        },
        // Carrera: Electromecánica
        Carrera {
            nombre: "Electromecánica".to_string(),
            materias: vec![
                "Taller de ética".to_string(),
                "Cálculo diferencial".to_string(),
                "Introducción a la programación".to_string(),
                "Desarrollo sustentable".to_string(),
                "Química".to_string(),
                "Fundamentos de investigación".to_string(),
                "Estática".to_string(),
                "Cálculo integral".to_string(),
                "Álgebra lineal".to_string(),
                "Metrología y normalización".to_string(),
                "Tecnología de los materiales".to_string(),
                "Dibujo electromecánico".to_string(),
                "Dinámica".to_string(),
                "Cálculo vectorial".to_string(),
                "Procesos de manufactura".to_string(),
                "Electricidad y magnetismo".to_string(),
                "Mecánica de materiales".to_string(),
                "Probabilidad y estadística".to_string(),
                "Análisis y síntesis de mecanismos".to_string(),
                "Ecuaciones diferenciales".to_string(),
                "Termodinámica".to_string(),
                "Análisis de circuitos eléctricos de CD".to_string(),
                "Mecánica de fluidos".to_string(),
                "Electrónica analógica".to_string(),
                "Diseño de elementos de máquinas".to_string(),
                "Diseño e ingeniería asistidos por computadora".to_string(),
                "Transferencia de calor".to_string(),
                "Análisis de circuitos eléctricos de CA".to_string(),
                "Sistemas y máquinas de fluidos".to_string(),
                "Electrónica digital".to_string(),
                "Máquinas y equipos térmicos I".to_string(),
                "Ahorro de energía".to_string(),
                "Instalaciones eléctricas".to_string(),
            ],
        },
        // Carrera: Mecatrónica
        Carrera {
            nombre: "Mecatrónica".to_string(),
            materias: vec![
                "Química".to_string(),
                "Cálculo diferencial".to_string(),
                "Taller de ética".to_string(),
                "Dibujo asistido por computadora".to_string(),
                "Metrología y normalización".to_string(),
                "Fundamentos de investigación".to_string(),
                "Cálculo integral".to_string(),
                "Álgebra lineal".to_string(),
                "Ciencias e ingenierías de materiales".to_string(),
                "Programación básica".to_string(),
                "Estadística y control de calidad".to_string(),
                "Administración y contabilidad".to_string(),
                "Cálculo vectorial".to_string(),
                "Procesos de fabricación".to_string(),
                "Electromagnetismo".to_string(),
                "Estática".to_string(),
                "Métodos numéricos".to_string(),
                "Desarrollo sustentable".to_string(),
                "Ecuaciones diferenciales".to_string(),
                "Fundamentos de termodinámica".to_string(),
                "Mecánica de materiales".to_string(),
                "Dinámica".to_string(),
                "Análisis de circuitos eléctricos".to_string(),
                "Máquinas eléctricas".to_string(),
                "Electrónica analógica".to_string(),
                "Mecanismos".to_string(),
                "Análisis de fluidos".to_string(),
                "Taller de investigación 1".to_string(),
                "Actividades complementarias".to_string(),
                "Electrónica de potencia aplicada".to_string(),
                "Instrumentación".to_string(),
                "Diseño de elementos mecánicos".to_string(),
                "Electrónica digital".to_string(),
                "Vibraciones mecánicas".to_string(),
                "Taller de investigación 2".to_string(),
                "Dinámica de sistemas".to_string(),
                "Manufactura avanzada".to_string(),
                "Circuitos hidráulicos y neumáticos".to_string(),
                "Mantenimiento".to_string(),
                "Microcontroladores".to_string(),
                "Programación avanzada".to_string(),
                "Control".to_string(),
                "Formulación y evaluación de proyectos".to_string(),
                "Controladores lógicos programables".to_string(),
                "Servicio social".to_string(),
                "Robótica".to_string(),
                "Residencia profesional".to_string(),
                "Especialidad".to_string(),
            ],
        },
        // Carrera: Logística
        Carrera {
            nombre: "Logística".to_string(),
            materias: vec![
                "Introducción a la ingeniería en logística".to_string(),
                "Cálculo diferencial".to_string(),
                "Química".to_string(),
                "Fundamentos de administración".to_string(),
                "Dibujo asistido por computadora".to_string(),
                "Economía".to_string(),
                "Taller de ética".to_string(),
                "Cálculo integral".to_string(),
                "Probabilidad y estadística".to_string(),
                "Desarrollo humano y organizacional".to_string(),
                "Fundamentos de investigación".to_string(),
                "Contabilidad y costos".to_string(),
                "Cadena de suministro".to_string(),
                "Álgebra lineal".to_string(),
                "Estadística inferencial 1".to_string(),
                "Fundamentos de derecho".to_string(),
                "Mecánica clásica".to_string(),
                "Finanzas".to_string(),
                "Compras".to_string(),
                "Tipología del producto".to_string(),
                "Estadística inferencial 2".to_string(),
                "Entorno económico".to_string(),
                "Tópicos de ingeniería mecánica".to_string(),
                "Bases de datos".to_string(),
                "Almacenes".to_string(),
                "Inventarios".to_string(),
                "Investigación de operaciones 1".to_string(),
                "Higiene y seguridad".to_string(),
                "Procesos de fabricación y manejo de materiales".to_string(),
                "Mercadotecnia".to_string(),
                "Tráfico y transporte".to_string(),
                "Cultura de calidad".to_string(),
                "Investigación de operaciones 2".to_string(),
                "Desarrollo sustentable".to_string(),
                "Taller de investigación 1".to_string(),
                "Empaque, envase y embalaje".to_string(),
                "Actividades extraescolares".to_string(),
                "Servicio al cliente".to_string(),
                "Programación de procesos productivos".to_string(),
                "Modelos de simulación y logística".to_string(),
                "Legislación aduanera".to_string(),
                "Taller de investigación 2".to_string(),
                "Ingeniería económica".to_string(),
                "Innovación".to_string(),
                "Comercio internacional".to_string(),
                "Formulación y evaluación de proyectos".to_string(),
                "Geografía para el transporte".to_string(),
                "Servicio social".to_string(),
                "Residencia profesional".to_string(),
                "Especialidad".to_string(),
                "Gestión de".to_string(),
            ],
        },
    ]
}


// Endpoint para obtener solo los nombres de todas las carreras
#[get("/api/carreras")]
async fn obtener_nombres_carreras() -> impl Responder {
    info!("Obteniendo nombres de carreras");
    let carreras = obtener_carreras();
    let nombres: Vec<String> = carreras.iter().map(|c| c.nombre.clone()).collect();
    HttpResponse::Ok().json(nombres)
}

// Endpoint para obtener las materias de una carrera específica por su nombre
#[get("/api/materias/{nombre}")]
async fn obtener_materias_por_carrera(nombre: web::Path<String>) -> impl Responder {
    info!("Obteniendo materias para la carrera: {}", nombre);
    let carreras = obtener_carreras();
    for carrera in &carreras {
        if carrera.nombre.to_lowercase() == nombre.to_lowercase() {
            return HttpResponse::Ok().json(&carrera.materias);
        }
    }
    HttpResponse::NotFound().body("Carrera no encontrada")
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    // Configurar el logger
    env_logger::init();

    HttpServer::new(|| {
        App::new()
            .service(obtener_nombres_carreras)
            .service(obtener_materias_por_carrera)
    })
    .bind("127.0.0.1:8080")?
    .run()
    .await
}
